import { pgTable, pgSchema, index, foreignKey, uuid, numeric, text, timestamp, integer, boolean, date } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

export const chaindrain = pgSchema("chaindrain");


export const tier_stateInChaindrain = chaindrain.table("tier_state", {
	entity_id: uuid().primaryKey().notNull(),
	risk_score: numeric().notNull(),
	risk_tier: text().notNull(),
	coverage_tier: text().notNull(),
	tvl_factor: numeric(),
	mutability_factor: numeric(),
	audit_factor: numeric(),
	bounty_factor: numeric(),
	blast_radius_usd: numeric(),
	state: text().default('active'),
	last_state_change: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
	computed_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_ts_coverage").using("btree", table.coverage_tier.asc().nullsLast().op("text_ops")),
	index("idx_ts_risk_score").using("btree", table.risk_score.desc().nullsFirst().op("numeric_ops")),
	index("idx_ts_risk_tier").using("btree", table.risk_tier.asc().nullsLast().op("text_ops")),
	index("idx_ts_state").using("btree", table.state.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.entity_id],
			foreignColumns: [identityInChaindrain.entity_id],
			name: "tier_state_entity_id_fkey"
		}).onDelete("cascade"),
]);

export const dependency_fingerprintInChaindrain = chaindrain.table("dependency_fingerprint", {
	entity_id: uuid().primaryKey().notNull(),
	oracle_providers: text().array(),
	oracle_confidence: text(),
	bridge_dependencies: text().array(),
	bridge_confidence: text(),
	stablecoin_dependencies: text().array(),
	stablecoin_confidence: text(),
	dvn_configuration: text(),
	dvn_confidence: text(),
	dependency_sources: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_dep_bridges").using("gin", table.bridge_dependencies.asc().nullsLast().op("array_ops")),
	index("idx_dep_dvn").using("btree", table.dvn_configuration.asc().nullsLast().op("text_ops")),
	index("idx_dep_oracles").using("gin", table.oracle_providers.asc().nullsLast().op("array_ops")),
	index("idx_dep_stables").using("gin", table.stablecoin_dependencies.asc().nullsLast().op("array_ops")),
	foreignKey({
			columns: [table.entity_id],
			foreignColumns: [identityInChaindrain.entity_id],
			name: "dependency_fingerprint_entity_id_fkey"
		}).onDelete("cascade"),
]);

export const contract_fingerprintInChaindrain = chaindrain.table("contract_fingerprint", {
	entity_id: uuid().primaryKey().notNull(),
	primary_contract_address: text(),
	implementation_address: text(),
	proxy_pattern: text(),
	upgrade_authority_type: text(),
	admin_address: text(),
	multisig_threshold: integer(),
	timelock_delay_hours: numeric(),
	compiler_version: text(),
	verified_source: boolean(),
	uses_assembly: boolean(),
	external_call_count: integer(),
	audits_tier: integer(),
	audit_firms: text().array(),
	last_audit_date: date(),
	audit_links: text(),
	bug_bounty_program: text(),
	bug_bounty_max_payout_usd: numeric(),
	bug_bounty_immunefi_url: text(),
	bug_bounty_launch_date: date(),
	bug_bounty_updated_date: date(),
	bug_bounty_kyc_required: boolean(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_cf_admin_addr").using("btree", table.admin_address.asc().nullsLast().op("text_ops")),
	index("idx_cf_audits_tier").using("btree", table.audits_tier.asc().nullsLast().op("int4_ops")),
	index("idx_cf_contract").using("btree", table.primary_contract_address.asc().nullsLast().op("text_ops")),
	index("idx_cf_proxy").using("btree", table.proxy_pattern.asc().nullsLast().op("text_ops")),
	index("idx_cf_upgrade_auth").using("btree", table.upgrade_authority_type.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.entity_id],
			foreignColumns: [identityInChaindrain.entity_id],
			name: "contract_fingerprint_entity_id_fkey"
		}).onDelete("cascade"),
]);

export const identityInChaindrain = chaindrain.table("identity", {
	entity_id: uuid().primaryKey().notNull(),
	name: text().notNull(),
	website: text(),
	sector: text(),
	chain_deployments: text().array(),
	tvl_usd: numeric(),
	launch_date: date(),
	is_immutable: text(),
	is_permissionless: text(),
	defillama_slug: text(),
	coingecko_id: text(),
	match_source: text(),
	match_method: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_identity_chains").using("gin", table.chain_deployments.asc().nullsLast().op("array_ops")),
	index("idx_identity_sector").using("btree", table.sector.asc().nullsLast().op("text_ops")),
	index("idx_identity_slug").using("btree", table.defillama_slug.asc().nullsLast().op("text_ops")),
	index("idx_identity_tvl").using("btree", table.tvl_usd.desc().nullsLast().op("numeric_ops")),
]);
export const mvp_masterInChaindrain = chaindrain.view("mvp_master", {	entity_id: uuid(),
	name: text(),
	website: text(),
	sector: text(),
	chain_deployments: text(),
	tvl_usd: numeric(),
	launch_date: date(),
	is_immutable: text(),
	is_permissionless: text(),
	defillama_slug: text(),
	coingecko_id: text(),
	primary_contract_address: text(),
	implementation_address: text(),
	proxy_pattern: text(),
	upgrade_authority_type: text(),
	admin_address: text(),
	multisig_threshold: integer(),
	timelock_delay_hours: numeric(),
	compiler_version: text(),
	verified_source: boolean(),
	uses_assembly: boolean(),
	external_call_count: integer(),
	audits_tier: integer(),
	audit_firms: text(),
	last_audit_date: date(),
	audit_links: text(),
	bug_bounty_program: text(),
	bug_bounty_max_payout_usd: numeric(),
	bug_bounty_immunefi_url: text(),
	oracle_providers: text(),
	oracle_confidence: text(),
	bridge_dependencies: text(),
	bridge_confidence: text(),
	stablecoin_dependencies: text(),
	stablecoin_confidence: text(),
	dvn_configuration: text(),
	dvn_confidence: text(),
	dependency_sources: text(),
	risk_score: numeric(),
	risk_tier: text(),
	coverage_tier: text(),
	tvl_factor: numeric(),
	mutability_factor: numeric(),
	audit_factor: numeric(),
	bounty_factor: numeric(),
	blast_radius_usd: numeric(),
	state: text(),
	last_state_change: timestamp({ withTimezone: true, mode: 'string' }),
}).as(sql`SELECT i.entity_id, i.name, i.website, i.sector, i.chain_deployments, i.tvl_usd, i.launch_date, i.is_immutable, i.is_permissionless, i.defillama_slug, i.coingecko_id, cf.primary_contract_address, cf.implementation_address, cf.proxy_pattern, cf.upgrade_authority_type, cf.admin_address, cf.multisig_threshold, cf.timelock_delay_hours, cf.compiler_version, cf.verified_source, cf.uses_assembly, cf.external_call_count, cf.audits_tier, cf.audit_firms, cf.last_audit_date, cf.audit_links, cf.bug_bounty_program, cf.bug_bounty_max_payout_usd, cf.bug_bounty_immunefi_url, df.oracle_providers, df.oracle_confidence, df.bridge_dependencies, df.bridge_confidence, df.stablecoin_dependencies, df.stablecoin_confidence, df.dvn_configuration, df.dvn_confidence, df.dependency_sources, ts.risk_score, ts.risk_tier, ts.coverage_tier, ts.tvl_factor, ts.mutability_factor, ts.audit_factor, ts.bounty_factor, ts.blast_radius_usd, ts.state, ts.last_state_change FROM chaindrain.identity i LEFT JOIN chaindrain.contract_fingerprint cf USING (entity_id) LEFT JOIN chaindrain.dependency_fingerprint df USING (entity_id) LEFT JOIN chaindrain.tier_state ts USING (entity_id)`);